# Generated by Django 2.2.14 on 2020-07-28 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='text2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
