# Generated by Django 2.2.14 on 2020-07-28 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cv_text2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='text',
            new_name='text1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='text2',
            new_name='textEdu',
        ),
        migrations.AddField(
            model_name='cv',
            name='Education',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='IndustryExpertise',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='Key Skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='KeyExperience',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='Languages',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='Profile',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='textExp',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='textIndust',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='textLang',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='textProfile',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='textSkills',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
