# Generated by Django 2.2.14 on 2020-07-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200728_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='IndustryExpertise',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='Key Skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='KeyExperience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='Languages',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='text1',
        ),
    ]
